# Generated by Django 4.1.10 on 2023-10-17 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Select Commodity', max_length=255, null=True, verbose_name='Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Select State', max_length=255, null=True, verbose_name='State')),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Select Market', max_length=255, null=True, verbose_name='Market')),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='CommodityData')),
                ('avgPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('minPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('maxPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('priceUpdated', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 53, 49, 402519, tzinfo=datetime.timezone.utc), null=True)),
                ('prevprice', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.market')),
            ],
        ),
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='AllData')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('avgPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('minPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('maxPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('priceUpdated', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 53, 49, 403515, tzinfo=datetime.timezone.utc), null=True)),
                ('prevprice', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commodity')),
            ],
        ),
    ]
