# Generated by Django 5.0 on 2024-01-04 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscribers_alter_alldata_priceupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 4, 10, 18, 9, 977035, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='priceUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 4, 10, 18, 9, 976036, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
